### PR TITLE
fix for julia 1.6

### PR DESCRIPTION
**Pull request by clouds56**

### CODE REVIEW

**Comment by rob-luke** [comment]
I cant see why your workflow didnt activate the CIs. So I have added your test.yml file manually. Can you rebase and see if your other CIs now work?

Edit: I tried to do this for you, but you did not tick the box to give us permissions when you opened this PR.

**Comment by clouds56** [comment]
Updated, the CI is pending to approve to be run.

**Comment by rob-luke** [comment]
Looks like it's running. Good luck!

**Comment by clouds56** [comment]
It looks like some deps doesn't support julia before 1.2, shall we target to julia >= 1.3 as well?

**Comment by clouds56** [comment]
@rob-luke please approve the workflow again since it changed

**Comment by clouds56** [comment]
Now all test except AppVeyor (which is deleted) passed, do you have any idea how to disable it?

**Comment by rob-luke** [comment]
> Now all test except AppVeyor (which is deleted) passed, do you have any idea how to disable it?

Ill take care of it.

**Comment by rob-luke** [comment]
Thanks @clouds56!!

**Pull request merged**
