### PR TITLE
fixes some 0.5 depwarns and updates to SampledSignals 0.2.0

### LINKED ISSUE #2: eltype and nchannels are wrong on streams where MP3INFO conflicts with kwargs
It seems that in `savestream` the stream is initialized using the keyword args, but the stream properties are set from the `MP3INFO` argument.

To reproduce:

``` julia
julia> using MP3, SampledSignals

julia> osc = SinSource(Float32, 48000Hz, [440Hz])
SampledSignals.SinSource{Float32,SIUnits.SIQuantity{Int64,0,0,-1,0,0,0,0,0,0}}(48000 s⁻¹,SIUnits.SIQuantity{Int64,0,0,-1,0,0,0,0,0,0}[440 s⁻¹],0.0)

julia> buf = read(osc, 5s)
240000-frame, 1-channel SampleBuf{Float32, 2, SIUnits.SIQuantity{Int64,0,0,-1,0,0,0,0,0,0}}
5.0 s at 48000 s⁻¹
████████████████████████████████████████████████████████████████████████████████

julia> str = MP3.savestream("/tmp/sine.mp3", MP3.MP3INFO(buf), nchannels=2)
MP3.MP3FileSink("/tmp/sine.mp3",Ptr{Void} @0x00007fcf24e401e0,MP3.MP3INFO(240000,1,48000,Float32),IOStream(<file /tmp/sine.mp3>))

julia> nchannels(str)
1

julia> eltype(str)
Float32
```

I'd expect here that `eltype(str)` should return `Fixed{Int16, 15}` (because that's what the stream can accept), and `nchannels(str)` should return `2`. This way it can make use of the automatic conversion stuff in SampledSignals.

At some point we should also figure out how to export `loadstream` and `savestream`. I think in LibSndFile I just export them, but we don't want every package exporting their own versions. It might be worth talking to the FileIO folks to make those part of the FileIO API.

### PR DESCRIPTION
**Pull request by ssfrr**
also fixes #2

### CODE REVIEW

**Comment by ssfrr** [comment]
whoops, accidentally based this on the latest tagged version instead of master. Fixing and rebasing...

**Comment by ssfrr** [comment]
hrm, I just realized the SampledSignals isn't doing datatype conversion. I think I thought I didn't need to a while ago, but now I realize I do. I'll fix that and then fix up this PR.

**Comment by ssfrr** [comment]
OK, this should be in pretty good shape, though I haven't spent much time testing it out. Also, I tried enabling AppVeyor to see if it would build on windows but it seems that liblame and mpg123 aren't available in WinRPM, so the appveyor CI check is showing failed. I just re-disabled appveyor, as I figure we can leave that for the future.

This PR does a few things, as issues kept coming up as I was working on it. It brings things up-to-date with the recent SampledSignals API changes, and also fixes a couple issues (`unsafe_write` wasn't expected to be called multiple times, `samplerate` and friends weren't always reporting correctly), and it's now relying on SampledSignals for samplerate/channel/eltype conversions.

Something in here makes the tests run reeeeally slow with inlining is off, but it only needs to be off for test coverage, which we're not currently reporting anyways. Also, as of recent julia master, we don't need to turn off inlining for coverage, so I think when we want to start reporting coverage we'll just do it on the nightlies and everything should be hunky-dory.

In normal usage performance seems pretty much the same for loading/saving, but I'm tracking down a performance regression when saving with resampling. I expect it to be maybe a bit slower resampling in pure Julia rather than within liblame, but I think it can be faster than it is now.

**Comment by ssfrr** [comment]
@jongwook any thoughts on this PR? I've got another one queued up to work with the upcoming SampledSignals v0.3.0, but it currently depends on this PR.

**Comment by jongwook** [comment]
@ssfrr Oh, I didn't think that you were waiting on me. Thanks for the suggestions and improvements!

**Comment by ssfrr** [comment]
ah, sorry I was unclear. Thanks.

**Pull request merged**
